import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import terser from "@rollup/plugin-terser";

const twPaths = {
  "@codemirror/state":
    "$:/plugins/BurningTreeC/tiddlywiki-codemirror/lib/codemirror-state.js",
  "@codemirror/view":
    "$:/plugins/BurningTreeC/tiddlywiki-codemirror/lib/codemirror-view.js",
};

export default {
  input: "@codemirror/lint",
  external: Object.keys(twPaths),
  output: {
    file: "plugins/lint/files/codemirror-lint.js",
    format: "cjs",
    exports: "named",
    banner: `/*\\
title: $:/plugins/BurningTreeC/tiddlywiki-codemirror/plugins/lint/codemirror-lint.js
type: application/javascript
module-type: library

Bundled CodeMirror 6 lint module.
DO NOT EDIT – generated by Rollup.

\\*/
/*jslint node: true, browser: true */
"use strict";
`,
    paths: twPaths,
    esModule: false
  },
  plugins: [
    resolve({ browser: true }),
    commonjs(),
    terser({
      format: {
        comments: function(node, comment) {
          return comment.type === "comment2" && /^\\/.test(comment.value);
        }
      }
    })
  ]
};
